version: '3'
services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/bempp/work
      #- ../point/to/NAG:/opt/NAG/   # To include NAG license
    command: bash -c "pip install .[all] && /usr/local/bin/start-notebook.sh notebooks"